In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# dtype attribute

a = np.array([1,"a",True])
print(a.dtype)

b = np.array([1,2,3])
print(b.dtype)

c = np.array([1.1,2,3])
print(c.dtype)

<U21
int64
float64


In [4]:
"""
size 
"""
from sys import getsizeof

lst=[1]
print(getsizeof(list)) #int+object meta info

arr=np.array(list)
print(getsizeof(arr)) #int(dtypes)

lst1=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
print(getsizeof(lst1))

arr2=np.array(lst1)
print(getsizeof(arr2))

416
96
192
240


In [5]:
prices=[30,25,40,20,20,35,50,35]
#with a list
new_prices=[price-5 for price in prices]
print(new_prices)
#with a ndarray
prices_arr=np.array(prices)
prices_arr=prices_arr-5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [6]:
"""
exercise
"""
test_1=np.array([92,94,88,91,87])
test_2=np.array([79,100,86,93,91])
test_3=np.array([87,85,72,90,92])

test_3_fixed=test_3+2
print(test_3_fixed)

total_grade=test_1+test_2+test_3
print(total_grade)

final_grade=total_grade /3
print(final_grade)

jeremy_test_2=test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1=np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]


In [7]:
student_scores=np.array([test_1,test_2,test_3])
print(student_scores)

print(student_scores[2][0])

print(student_scores[:,4])
print(student_scores[:,-1])

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]
[87 91 92]


In [8]:
"""
logical poerations
"""
a=np.array([10,2,2,4,5,3,9,8,9,7])
mask=a>5
print(mask)

#부분집합 구하기(selection)
selected=a[a>5]
print(selected)

#논리식 결합
selected=a[(a>5)|(a<3)]
print(selected)

sclceted=a[(a>6)|(a<4)]
print(selected)

selected=a[(a>4)&(a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  9  8  9  7]
[10  2  2  9  8  9  7]
[5 7]
